#!/usr/bin/env ruby

puts RUBY_DESCRIPTION

ENV['CONSOLE_DEVICE'] ||= 'stdout'
ENV['LOG_COLOR'] ||= 'on'
if ENV['LOG_LEVEL']
  ENV['LOGGER'] ||= 'on'
else
  ENV['LOG_LEVEL'] ||= 'info'
end
ENV['LOGGER'] ||= 'on'
ENV['LOG_OPTIONAL'] ||= 'on'

require_relative '../init'
require 'process_host'
require_relative './service'

Service.start
